module.exports = {
    inputDir: "./icons",
    outputDir: "./dist",
    fontTypes: ["woff2"],
    assetTypes: [],
    codepoints: {
        "spread-none": 0xE001,
        "spread-odd": 0xE002,
        "spread-even": 0xE003,
        "scroll-page": 0xE004,
        "scroll-vertical": 0xE005,
        "scroll-horizontal": 0xE006,
        "scroll-wrapped": 0xE007,
        "zoom-in": 0xE008,
        "zoom-out": 0xE009,
        "rotate-left": 0xE00A,
        "rotate-right": 0xE00B,
        "page-first": 0xE00C,
        "page-last": 0xE00D,
        "page-prev": 0xE00E,
        "page-next": 0xE00F,
        "view-layers": 0xE010,
        "view-outline": 0xE011,
        "view-thumbnail": 0xE012,
    }
}
